"""init tables

Revision ID: 43bff38566cb
Revises: 
Create Date: 2025-11-24 16:16:53.007370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bff38566cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('ELDERLY_HISTORY',
    # sa.Column('region_name', sa.String(length=50), nullable=False),
    # sa.Column('year', sa.Integer(), nullable=False),
    # sa.Column('elderly_pop', sa.Integer(), nullable=False),
    # sa.PrimaryKeyConstraint('region_name', 'year')
    # )
    op.create_table('REGION',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ELDERLY_STATS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('single_house_total', sa.Integer(), nullable=True),
    sa.Column('apartment_total', sa.Integer(), nullable=True),
    sa.Column('row_house_total', sa.Integer(), nullable=True),
    sa.Column('multi_house_total', sa.Integer(), nullable=True),
    sa.Column('non_residential_housing_total', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('aging_index', sa.Float(), nullable=True),
    sa.Column('population_total', sa.Integer(), nullable=True),
    sa.Column('population_male', sa.Integer(), nullable=True),
    sa.Column('population_female', sa.Integer(), nullable=True),
    sa.Column('population_change_count', sa.Integer(), nullable=True),
    sa.Column('population_growth_ratio', sa.Float(), nullable=True),
    sa.Column('single_household_ratio', sa.Float(), nullable=True),
    sa.Column('under_20', sa.Integer(), nullable=True),
    sa.Column('age_65_over', sa.Integer(), nullable=True),
    sa.Column('age_0_14', sa.Integer(), nullable=True),
    sa.Column('cpi_index', sa.Float(), nullable=True),
    sa.Column('LOW_INC_65_79_RATIO', sa.Float(), nullable=True),
    sa.Column('LOW_INC_80_PLUS_RATIO', sa.Float(), nullable=True),
    sa.Column('basic_pension_recipient_count', sa.Integer(), nullable=True),
    sa.Column('basic_pension_recipient_ratio', sa.Float(), nullable=True),
    sa.Column('alone_household_count', sa.Integer(), nullable=True),
    sa.Column('elderly_population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['REGION.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'year', name='uq_elderly_stats_region_year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ELDERLY_STATS')
    op.drop_table('REGION')
    # op.drop_table('ELDERLY_HISTORY')
    # ### end Alembic commands ###
